services:
  - type: web
    name: exo-cloud-exam-62465
    region: frankfurt  
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASEURL
        fromDatabase:
          name: mydb
          property: connectionString

databases:
  - name: exo-cloud-db
    databaseName: mydbname
    region: frankfurt
    plan: free